Remove obsolete callback
openBackhaul/ApplicationLayerTopology pull request #131
Opened 2022-12-03 17:47 UTC by openBackhaul

NewApplicationCausesRequestForLatestTopologyInformation  removed from /v1/regard-application

Fixes #66

2022-12-03 17:49 UTC, openBackhaul commented
Will create a conflict after merging pull-request "Reference CONFIGfile structure in callback uri" #130.
Deleting the affected callback is the correct resolution.

2022-12-05 06:46 UTC, IswaryaaS requested changes

2022-12-05 06:46 UTC, IswaryaaS commented on ApplicationLayerTopology+forwardings.yaml
> -      - server-name: /v1/list-ltps-and-fcs
While removing entries for /v1/list-ltps-and-fcs, the corresponding entry of /v1/list-ltps-and-fcs :: alt-2-0-0-op-s-bm-008 in ServiceRequestCausesLoggingRequest is also deleted in forwardings file. It needs to be added again.

2022-12-05 06:46 UTC, IswaryaaS commented on ApplicationLayerTopology.yaml
> +          url: #[/core-model-1-4:network-control-domain/control-construct=alt-2-0-0/logical-termination-point=alt-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-
As mentioned in comment https://github.com/openBackhaul/ApplicationLayerTopology/pull/130/#discussion_r1039180709, can we make the uuid(s) in URI to be specific to OKM application. Kindly let me know your views

2022-12-05 09:13 UTC, IswaryaaS commented on ApplicationLayerTopology.yaml
> +          url: #[/core-model-1-4:network-control-domain/control-construct=alt-2-0-0/logical-termination-point=alt-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-
This comment will become obsolete from decision made in https://github.com/openBackhaul/ApplicationLayerTopology/issues/59#issuecomment-1336986967. Hence resolving this conversation

2022-12-05 09:31 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> -      - server-name: /v1/list-ltps-and-fcs
Changed as proposed.
Many thanks for indicating.

2022-12-05 10:01 UTC, IswaryaaS approved these changes

2022-12-05 13:28 UTC, merged