Remove ApiSegment from UUIDs of HttpClients/Servers and TcpClients/Servers
openBackhaul/ApplicationLayerTopology pull request #159
Opened 2022-12-13 09:16 UTC by kmohr-soprasteria

Fixes #138

2022-12-13 14:27 UTC, IswaryaaS requested changes

2022-12-13 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology+profileInstances.yaml
>        datatype: 'string'
Path to attributes in ApplicationLayerTopology+profileInstances.yaml is still containing /core-model-1-4:network-control-domain/control-construct. This needs to be updated to /core-model-1-4:control-construct as a part of seggreagating application-data from config data as per issue https://github.com/openBackhaul/ApplicationLayerTopology/issues/132. This file was missed to get updated in https://github.com/openBackhaul/ApplicationLayerTopology/pull/136.

2022-12-13 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology+services.yaml
> +      uuid: alt-2-0-0-tcp-s-001
Shall we remove the entry for alt-2-0-0-tcp-s-001 from services.yaml file, since it has become obsolete and is not being maintained in config file.

2022-12-13 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology.yaml
> +              server-ltp: ['cc-1-0-0-http-s-000']
In this file, we could find a pattern \*-http-s-\*-000 in multiple places pointing to http-s attributes in ElasticSearch. Here, the second occurence of \* indicates the api-segment which needs to be removed. So, the pattern should be updated as \*-http-s-000

2022-12-13 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology.yaml
>                          topology-application-release-number: '2.0.0'
line 1203 : /v1/list-applications :: In example 2 of this service, the ip-address and port corresponds to version 2.0.0 of TypeApprovalRegister. So, can we update the release-number of TAR to 2.0.0 instead of 1.0.0

2022-12-13 16:26 UTC, IswaryaaS commented on ApplicationLayerTopology.yaml
>                          topology-application-release-number: '2.0.0'
As per comment https://github.com/openBackhaul/ExecutionAndTraceLog/pull/153#discussion_r1047382078, can we also update TAR data in line 1203 (example of /v1/list-applications)

2022-12-13 17:09 UTC, openBackhaul commented on ApplicationLayerTopology+services.yaml
> +      uuid: alt-2-0-0-tcp-s-001
Changed as proposed.

2022-12-13 17:14 UTC, openBackhaul commented on ApplicationLayerTopology.yaml
> +              server-ltp: ['cc-1-0-0-http-s-000']
Changed as proposed.

2022-12-13 17:18 UTC, openBackhaul commented on ApplicationLayerTopology.yaml
>                          topology-application-release-number: '2.0.0'
Changed protocol to HTTP.

2022-12-14 09:43 UTC, IswaryaaS approved these changes

2022-12-14 09:52 UTC, merged