Change sequence number of /v1/notify-link-updates
openBackhaul/ApplicationLayerTopology pull request #232
Opened 2023-01-16 09:48 UTC by openBackhaul

Fixes #231

2023-01-17 07:19 UTC, IswaryaaS approved these changes
Requesting change for a small typo. Other changes looks fine. 
Once updated we can merge it to develop branch.

2023-01-17 07:19 UTC, IswaryaaS commented on spec/ApplicationLayerTopology.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=alt-2-0-0-op-c-*-*-*-*-002/layer-protocol=0/operation-client-interface-1-0:operation-client-interface
The placeholder for "ApiSegment" has been missed in the pattern. 
The uuid pattern in description to be updated as "alt-2-0-0-op-c-_is_-\*-\*-\*-\*-002" in line 3288 (where "is" is missing)

(The other updates are fine as per expectation0

2023-01-17 07:21 UTC, IswaryaaS requested changes
Changes requested in https://github.com/openBackhaul/ApplicationLayerTopology/pull/232#discussion_r1071822511

2023-01-23 11:40 UTC, openBackhaul commented on spec/ApplicationLayerTopology.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=alt-2-0-0-op-c-*-*-*-*-002/layer-protocol=0/operation-client-interface-1-0:operation-client-interface
Changed as proposed.

2023-01-23 11:42 UTC, openBackhaul commented
Added http->tcp-client-interface-1-0:PROTOCOL_TYPE_HTTP for fixing #233

2023-01-23 15:39 UTC, IswaryaaS approved these changes

2023-01-23 16:12 UTC, merged