issue-239 : added Elasticsearch and proper mapping for control-construct
openBackhaul/ApplicationLayerTopology pull request #242
Opened 2023-02-15 14:17 UTC by DanaSunal

2023-02-17 15:05 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-02-20 17:01 UTC, vanithavalluripalli9 requested changes

2023-02-21 15:51 UTC, DanaSunal commented on server/service/individualServices/ElasticsearchPreparation.js
> +                        'profile-collection': { type: 'flattened' },
Done

2023-02-24 09:46 UTC, vanithavalluripalli9 requested changes

2023-02-24 09:46 UTC, vanithavalluripalli9 commented on server/controllers/ElasticsearchClient.js
> +  responseBuilder.buildResponse(res, responseCode, response);
can we add forwarding to the OamLog

2023-02-24 09:46 UTC, vanithavalluripalli9 commented on server/controllers/ElasticsearchClient.js
> +  responseBuilder.buildResponse(res, responseCode, response);
can we add forwarding to OamLog

2023-02-24 10:02 UTC, DanaSunal commented on server/controllers/ElasticsearchClient.js
> +  responseBuilder.buildResponse(res, responseCode, response);
Why? The response here is a courtesy to let operator know, he shouldn't be trying this operation.

2023-02-24 10:43 UTC, vanithavalluripalli9 commented on server/controllers/ElasticsearchClient.js
> +  responseBuilder.buildResponse(res, responseCode, response);
OamLog application is used to log all the requests that are recieved in OamLayer even if it is a bad request

2023-02-26 12:48 UTC, DanaSunal commented on server/controllers/ElasticsearchClient.js
> +  responseBuilder.buildResponse(res, responseCode, response);
I created #253 because I am not sure what solution will be correct. Please ignore this part for now, I will create new PR if needed, once #253 is resolved.

2023-02-27 06:07 UTC, vanithavalluripalli9 approved these changes
Approved

2023-02-27 06:07 UTC, merged