issue-205 : record callback response to ES
openBackhaul/ApplicationLayerTopology pull request #244
Opened 2023-02-16 13:35 UTC by DanaSunal

Fixes #205.

Tied to (PR 576)[https://github.com/openBackhaul/ApplicationPattern/pull/576]

2023-02-16 14:32 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9 , please squash commits when merging.

2023-02-24 09:52 UTC, vanithavalluripalli9 requested changes

2023-02-24 09:52 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +const { elasticsearchService, getIndexAliasAsync } = require('onf-core-model-ap/applicationPattern/services/ElasticsearchService');
can we add onf-core-model-ap package to package.json file as it is required to make this work .

2023-02-26 13:32 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +const { elasticsearchService, getIndexAliasAsync } = require('onf-core-model-ap/applicationPattern/services/ElasticsearchService');
Done in previous PR.

2023-02-27 06:17 UTC, vanithavalluripalli9 approved these changes

2023-02-27 06:17 UTC, merged