issue-193 : create links for regarded applications operation server
openBackhaul/ApplicationLayerTopology pull request #247
Opened 2023-02-20 14:05 UTC by DanaSunal

Merge after #245

2023-02-20 14:07 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-02-24 09:56 UTC, vanithavalluripalli9 requested changes

2023-02-24 09:56 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +  let uuid = construct["core-model-1-4:control-construct"]["uuid"];
these changes are part of pull request #244 maybe we can remove this

2023-02-26 14:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +  let uuid = construct["core-model-1-4:control-construct"]["uuid"];
Done.

2023-03-02 12:00 UTC, vanithavalluripalli9 approved these changes

2023-03-02 12:01 UTC, merged