Resolved Support Version 2.0.0 changes for disregard-application
openBackhaul/ApplicationLayerTopology pull request #248
Opened 2023-02-22 04:09 UTC by ManasaBM1

Fixes #207

2023-02-22 04:11 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-02-24 08:57 UTC, DanaSunal approved these changes

2023-02-24 09:02 UTC, DanaSunal requested changes
Fix the merge conflict please.

2023-02-27 04:53 UTC, ManasaBM1 commented
done

2023-02-28 08:06 UTC, merged