Resolved Support Version 2.0.0 changes for regard-application
openBackhaul/ApplicationLayerTopology pull request #249
Opened 2023-02-22 04:37 UTC by ManasaBM1

Fixes #206

2023-02-22 04:45 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-02-24 08:48 UTC, DanaSunal requested changes
Mappings should be in one file, not a file per method.

2023-02-24 08:48 UTC, DanaSunal commented on server/service/individualServices/IndividualServicesOperationsMapping.js
> +module.exports.individualServicesOperationsMapping =
Mapping should be just one file. Take a look at BasicServicesOperationsMapping in ApplicationPattern.

2023-02-27 05:03 UTC, ManasaBM1 commented on server/service/individualServices/IndividualServicesOperationsMapping.js
> +module.exports.individualServicesOperationsMapping =
ok done

2023-03-01 08:25 UTC, DanaSunal requested changes

2023-03-01 08:25 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +const httpServerInterface = require('onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/HttpServerInterface');
Already on line 27

2023-03-01 08:25 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +
Already on line 30

2023-03-01 08:25 UTC, DanaSunal commented on server/service/individualServices/IndividualServicesOperationsMapping.js
> +}
Format this json.

2023-03-01 10:31 UTC, ManasaBM1 commented on server/service/IndividualServicesService.js
> +const httpServerInterface = require('onf-core-model-ap/applicationPattern/onfModel/models/layerProtocols/HttpServerInterface');
removed

2023-03-01 10:31 UTC, ManasaBM1 commented on server/service/individualServices/IndividualServicesOperationsMapping.js
> +}
done

2023-03-01 11:02 UTC, DanaSunal approved these changes

2023-03-01 11:03 UTC, merged