Resolved Support Version 2.0.0 changes for /v1/notify-link-updates
openBackhaul/ApplicationLayerTopology pull request #251
Opened 2023-02-23 04:46 UTC by ManasaBM1

Fixes #226

2023-02-23 04:58 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-02-24 08:41 UTC, DanaSunal requested changes
Please rename the mapping file. Files should start with Uppercase letters. Also not sure what means the 'notify' suffix, but if it's needed there, make the whole name CamelCase.

2023-02-27 05:05 UTC, ManasaBM1 commented
Done . mapped to single file

2023-03-01 11:09 UTC, DanaSunal approved these changes

2023-03-01 11:09 UTC, merged