Resolved Integrate version 2.0.0 BasicServices and ApplicationPattern
openBackhaul/ApplicationLayerTopology pull request #252
Opened 2023-02-23 04:56 UTC by ManasaBM1

Fixes #227

2023-02-23 04:57 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-02-24 08:35 UTC, DanaSunal commented on server/package.json
> +    "onf-core-model-ap": "2.0.0-alpha.3"
Please change it to latest as per openBackhaul/ExecutionAndTraceLog#195

2023-03-02 04:50 UTC, ManasaBM1 commented on server/package.json
> +    "onf-core-model-ap": "2.0.0-alpha.3"
Done

2023-03-02 04:52 UTC, ManasaBM1 commented on server/package.json
> +    "onf-core-model-ap": "2.0.0-alpha.3"
Done

2023-03-02 09:49 UTC, DanaSunal requested changes
Some files from the inline applicationPattern are needed in IndividualServices, please check and keep them.

2023-03-02 09:49 UTC, DanaSunal commented on server/package.json
> +    "openbackhaul-oas3-tools": "2.3.1-alpha.1"
packages should be in alphabetical order.

2023-03-06 06:14 UTC, DanaSunal approved these changes

2023-03-06 06:14 UTC, merged