Support Version 2.0.0 changes for /v1/add-operation-client-to-link
openBackhaul/ApplicationLayerTopology pull request #255
Opened 2023-03-01 10:18 UTC by vanithavalluripalli9

Fixes #219

2023-03-01 10:19 UTC, vanithavalluripalli9 commented
Reviewer is @DanaSunal

2023-03-02 08:01 UTC, DanaSunal requested changes

2023-03-02 08:49 UTC, DanaSunal commented on server/applicationPattern/onfModel/models/NetworkControlDomain.js
> +        let client = await elasticsearchService.getClient();
getClient has arguments, in this case, both are mandatory

2023-03-02 08:51 UTC, DanaSunal commented on server/applicationPattern/onfModel/models/NetworkControlDomain.js
> +          let _link = linkList[i]._source;
To avoid doing this, consider using ElasticsearchService/createResultArray

2023-03-03 12:35 UTC, vanithavalluripalli9 commented on server/applicationPattern/onfModel/models/Link.js
> +                            source: "for (int i=0;i< ctx._source['link-port'].length;i++){ if (ctx._source['link-port'][i]['local-id'] == params['local-id']) {ctx._source['link-port'].remove(i)}}",
Thank you for indicating . I was not aware of it . Made changes for using lambda.

2023-03-03 12:37 UTC, vanithavalluripalli9 commented on server/applicationPattern/onfModel/models/NetworkControlDomain.js
> +        let client = await elasticsearchService.getClient();
Done.

2023-03-03 12:37 UTC, vanithavalluripalli9 commented on server/applicationPattern/onfModel/models/NetworkControlDomain.js
> +          let _link = linkList[i]._source;
Done . Thank you for indicating

2023-03-03 13:10 UTC, DanaSunal requested changes
All the files should be moved out of applicationPattern/ directory, since we probably want to delete them as whole

2023-03-03 13:10 UTC, DanaSunal commented on server/applicationPattern/onfModel/models/NetworkControlDomain.js
> +        let client = await elasticsearchService.getClient(false, ELASTICSEARCH_CLIENT_CC_UUID);
You can directly filter in Elasticsearch based on applicationName and releaseNumber  - https://www.elastic.co/guide/en/elasticsearch/reference/7.16/query-dsl-bool-query.html

2023-03-16 17:19 UTC, closed without merging