Issue 211
openBackhaul/ApplicationLayerTopology pull request #268
Opened 2023-03-09 10:46 UTC by DanaSunal

Fixes #211

2023-03-10 12:00 UTC, vanithavalluripalli9 requested changes

2023-03-10 14:17 UTC, DanaSunal commented on server/service/individualServices/LinkServices.js
> -        try {
The service remove-operation-client-to-link should also use the new method from this file (that is correctly called deleteLinkPortAsync - line 132)

2023-03-10 14:30 UTC, vanithavalluripalli9 commented on server/service/individualServices/LinkServices.js
> -        try {
Thank you for indicating . Yeah, it is indeed using the correct method deleteLinkPortAsync and pull request #255 also has the same method contents . The method deleteLinkPortAsync is being called from deleteLinkAsync

2023-03-14 10:25 UTC, vanithavalluripalli9 submitted a review, later dismissed

2023-03-14 10:25 UTC, vanithavalluripalli9 commented on server/service/individualServices/LinkServices.js
> +      deleteLinkAsync(res.body.hits.hits[0]._id);
For now there is no scenario where we will be deleting the whole link . so we can remove this

2023-03-17 08:31 UTC, vanithavalluripalli9 requested changes

2023-03-17 08:31 UTC, vanithavalluripalli9 commented on server/service/individualServices/LinkServices.js
> +  let esUuid = await ElasticsearchPreparation.getCorrectEsUuid(true);
As the method is not used deleteLinkAsync(linkId) anywhere can we remove it and restore the older one of deleteLinkAsync(linkUuid , consumingOperationUuid )

2023-03-17 09:11 UTC, DanaSunal commented on server/service/individualServices/LinkServices.js
> +  let esUuid = await ElasticsearchPreparation.getCorrectEsUuid(true);
Done.

2023-03-17 09:27 UTC, vanithavalluripalli9 approved these changes

2023-03-17 09:27 UTC, merged