Support Version 2.0.0 changes for update-fc
openBackhaul/ApplicationLayerTopology pull request #273
Opened 2023-03-13 13:58 UTC by vanithavalluripalli9

Fixes #214

2023-03-13 16:23 UTC, DanaSunal requested changes

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
>        let controlConstructUuid = figureOutControlConstructUuid(forwardingConstructUuid);
You can find correct control construct by searching in ES for forwardingConstructUuid.

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +const ELASTICSEARCH_CLIENT_LINKS_UUID = "alt-2-0-1-es-c-es-1-0-0-001";
Not used.

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +const ELASTICSEARCH_CLIENT_CC_UUID = "alt-2-0-1-es-c-es-1-0-0-000";
Given the amount of methods, I'd create 'ForwardingService' that would group methods dealing with FC and FC-ports and not pollute IndividualServices.

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      let indexAlias = await getIndexAliasAsync("ELASTICSEARCH_CLIENT_CC_UUID");
Value should be used here, not the name of the constant.

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +async function updateForwardingConstrutList(forwardingConstructListToBeUpdated, forwardingConstructUuid) {
typo in the name of the method -> updateForwardingConstrucTList

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +        filter_path: "hits.hits._id,hits.hits._source.forwarding-domain",
Given how this method is used, you want actually the forwardingConstructList, you can filter it in the request.

2023-03-13 16:23 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +                "uuid": forwardingConstructUuid,
not used

2023-03-14 11:45 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
>        let controlConstructUuid = figureOutControlConstructUuid(forwardingConstructUuid);
There are scenarios where forwardingConstructUuid might not be present in controlconstruct and we have to add it . So, got the control construct and checked whether the forwardingConstructUuid exists if not added sand if present replaced

2023-03-14 11:45 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +const ELASTICSEARCH_CLIENT_LINKS_UUID = "alt-2-0-1-es-c-es-1-0-0-001";
Removed

2023-03-14 11:46 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +const ELASTICSEARCH_CLIENT_CC_UUID = "alt-2-0-1-es-c-es-1-0-0-000";
Created the ForwardinService file as suggested and moved the methods

2023-03-14 11:52 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +        filter_path: "hits.hits._id,hits.hits._source.forwarding-domain",
Yes tried it . But , was not able to filter only forwardingConstructList . So, fetched forwarding-domain as it didn't make much difference. If you could suggest a way is ES to fetch only forwardingConstructList will try it .Thank you

2023-03-14 11:52 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +                "uuid": forwardingConstructUuid,
Done.

2023-03-14 12:59 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +        filter_path: "hits.hits._id,hits.hits._source.forwarding-domain",
filter_path: "hits.hits._id,hits.hits._source.forwarding-domain.forwarding-construct"

2023-03-14 13:14 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +        filter_path: "hits.hits._id,hits.hits._source.forwarding-domain",
Thank you . Tried this before but output was something like forwarding-domain:[{forwarding-construct}] which didn't make much difference than the current one .

2023-03-14 14:02 UTC, DanaSunal approved these changes

2023-03-14 14:02 UTC, merged