Update services "Application existence check" needs to be updated
openBackhaul/ApplicationLayerTopology pull request #276
Opened 2023-03-15 14:02 UTC by vanithavalluripalli9

Fixes #146

2023-03-15 14:03 UTC, vanithavalluripalli9 commented
Reviewer is @DanaSunal

2023-03-16 09:36 UTC, DanaSunal requested changes

2023-03-16 09:36 UTC, DanaSunal commented on server/service/individualServices/ControlConstructService.js
> +   if (Object.keys(res.body.hits.hits).length === 0) {
ES will return empty body object if no control-construct was found, which means this check will fail on 'cannot read property hits on undefined'.

2023-03-16 09:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
This is not needed here. The method 'getForwardingDomainFromControlConstruct' already does this check, no need to double check it.

2023-03-16 09:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +
No need for this here either, my PR #268 already takes care of that.

2023-03-16 09:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
Same as with delete-fc-port.

2023-03-16 09:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
Same as with delete-fc-port.

2023-03-16 09:36 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
PR #267 takes care of this.

2023-03-16 16:37 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
Done

2023-03-16 16:37 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +
Done

2023-03-16 16:37 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
Done

2023-03-16 16:37 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      await checkApplicationExists(controlConstructUuid);
Done

2023-03-16 16:41 UTC, vanithavalluripalli9 commented on server/service/individualServices/ControlConstructService.js
> +   if (Object.keys(res.body.hits.hits).length === 0) {
ES was returning body.hits.hits as empty object . where as body was containing hits object . So , even when controlconstruct was not present in ES , it was not throwing the error .

2023-03-17 09:43 UTC, DanaSunal submitted a review, later dismissed

2023-03-17 09:43 UTC, DanaSunal commented on server/service/individualServices/ControlConstructService.js
> +   if (Object.keys(res.body.hits.hits).length === 0) {
I see... when the filter path is hits.hits, it returns `{
  "hits" : {
    "hits" : [ ]
  }
}` when the filter path is hits.hits._source it returns an empty object. `{}`

2023-03-17 09:43 UTC, DanaSunal commented on server/service/individualServices/ControlConstructService.js
> +const ELASTICSEARCH_CLIENT_CC_UUID = "alt-2-0-1-es-c-es-1-0-0-000";
Use ElasticsearchPreparation.

2023-03-17 10:19 UTC, merged