Documentation for Elasticsearch usage in ALT
openBackhaul/ApplicationLayerTopology pull request #284
Opened 2023-03-20 11:35 UTC by DanaSunal

2023-04-07 08:52 UTC, DanaSunal commented
Reviewer is @IswaryaaS

2023-04-11 07:35 UTC, IswaryaaS requested changes
1. Requesting you to please create an issue for including documentation and link this PR to the issue. 
2. we need to include the main.md file in /doc/ folder and use this as root file to include all other concepts. 
Please refer to https://github.com/openBackhaul/RegistryOffice/blob/develop/doc
3. After including main.md file, we need to refer it in [Description](https://github.com/DanaSunal/ApplicationLayerTopology/tree/docs#description) and [Resources](https://github.com/DanaSunal/ApplicationLayerTopology/tree/docs#resources) in Readme.md . Please refer to https://github.com/openBackhaul/RegistryOffice#readme

2023-04-17 04:56 UTC, IswaryaaS approved these changes

2023-04-17 04:57 UTC, IswaryaaS reviewed
Requesting second level review from @vanithavalluripalli9

2023-04-17 05:06 UTC, IswaryaaS requested changes
Also in readme.md file, along with adding url to resources column, we need to include reference to main.md in [Description](https://github.com/DanaSunal/ApplicationLayerTopology/tree/docs#description) similar to https://github.com/openBackhaul/RegistryOffice#description

2023-04-17 05:06 UTC, IswaryaaS commented on doc/ElasticsearchUsage.md
> +
I understand for comment #4 of https://github.com/openBackhaul/ApplicationLayerTopology/pull/284#pullrequestreview-1378619863 has been missed to address. 
"Also requesting you to include reference of ES documents from ApplicationPattern repository, so when a new user starts with ALT, he can go to AP documents to understand the basic or any further information required.", we could include the link after it is merged to AP.

2023-04-17 06:57 UTC, vanithavalluripalli9 requested changes

2023-04-17 06:57 UTC, vanithavalluripalli9 commented on doc/ElasticsearchUsage.md
> +
can we mention why we are not using service record policy in ALT

2023-04-17 13:53 UTC, DanaSunal commented on doc/ElasticsearchUsage.md
> +
Yes,sorry, missed that one. Fixed now.

2023-04-17 13:53 UTC, DanaSunal commented on doc/ElasticsearchUsage.md
> +
Done.

2023-04-19 04:32 UTC, IswaryaaS approved these changes

2023-05-08 08:15 UTC, merged