Resolve correct the tcpserverInterface  in bequeathYourDataAndDie and include the toString() method
openBackhaul/ApplicationLayerTopology pull request #291
Opened 2023-04-11 05:10 UTC by ManasaBM1

Fixes #290

2023-04-11 05:11 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-04-24 11:27 UTC, PrathibaJee requested changes

2023-04-24 11:27 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +        if (JSON.stringify(address) ===JSON.stringify(serverAddress) && port === serverPort) {
Could you please kindly remove the lines 155 to 157 , as data trasfer is must in order to enable the forwardings and to make this service as idempotent. Thanks. Let me know if you have a different view.
( cc : @IswaryaaS )

2023-05-10 12:47 UTC, PrathibaJee approved these changes
Requested changes are resolved. Many thanks.

2023-05-10 12:48 UTC, merged