Issue 297 : added backendTime
openBackhaul/ApplicationLayerTopology pull request #298
Opened 2023-04-22 20:03 UTC by DanaSunal

2023-04-24 09:29 UTC, PrathibaJee requested changes
I could able to see changes included for the following methods, 
deleteFcPort
listEndPointsOfLink
listLinkUuids

I have few review comments and questions. 
Kindly please provide your views. 
Many thanks.

2023-04-24 09:29 UTC, PrathibaJee commented on server/controllers/IndividualServices.js
> +        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, responseBody.took);
We are recording the backendTime in case of positive execution , whereas in the catch block , this is not getting captured. 
As a part of listEndPointsOfLink service , the following two services are called , 
1st call : LinkServices.getLinkAsync
2nd call : ControlConstructService.getControlConstructAsync
and "took" is the consolidated value of both this call.
If there is a failure in the 2nd call , then we may miss to record the time spent in the first call.
Kindly please let me know your views in this regard.

2023-04-24 10:47 UTC, DanaSunal commented on server/controllers/IndividualServices.js
> +        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, responseBody.took);
You are correct, backendTime is not being recorded in case of failure. My understanding is that it's simply there to check for operations that take long time and if they are found, to optimize them to reduce the backendTime. If this is the case, then I do not see a reason to record the time, when a method fails, because it's not what the method should normally do and it should be fixed.

2023-04-24 10:47 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +                "forwarding-domain.forwarding-construct.uuid": "aa-2-0-1-op-fc-bm-000"
Sorry, typo from testing.

2023-04-24 10:47 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +  if (response && response.body.updated === 1) {
Same as above comment. If there was a failure I do not see any informative reason to keep the backendTime other than 0. The whole execution time of the method is already recorded in exec time.

2023-04-24 10:47 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +  return { "body" : { "link-end-point-list": linkEndPointList }, "took" : took };
Why? What would be the action with the error?

2023-04-24 10:47 UTC, DanaSunal commented on server/service/individualServices/ControlConstructService.js
> +      filter_path: "hits.hits",
Correct, good catch.

2023-04-24 12:13 UTC, PrathibaJee commented on server/controllers/IndividualServices.js
> +        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, responseBody.took);
> My understanding is that it's simply there to check for operations that take long time and if they are found, to optimize them to reduce the backendTime.

Yes,  it will be one of the usage of this header. 
I have a little different view , please find as below, 
If backendTime header value would be 0 for all the failure cases, then , this will give an impression that there is no call to the backend. 
If there is a time spent in the backend, then recording it would be more transparent. What do you think ?

2023-04-24 12:15 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +  return { "body" : { "link-end-point-list": linkEndPointList }, "took" : took };
Lets resolve this comment after deciding on this https://github.com/openBackhaul/ApplicationLayerTopology/pull/298#discussion_r1175196473

2023-04-25 08:16 UTC, DanaSunal commented on server/controllers/IndividualServices.js
> +        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, responseBody.took);
Why do we need to know if there was a call to backend?
The only thing concerning us in failed requests should be finding why they failed and how to fix it and not how long a call to some backend app took.
Implementing time measure that should work, even where code can fail at any line, is a solution that will add a lot of complexity to the code and I simply fail to see the benefit in return. In case of failure, there should be logs that would tell us what is going on.

2023-04-25 10:24 UTC, PrathibaJee commented on server/controllers/IndividualServices.js
> +        let responseHeader = await restResponseHeader.createResponseHeader(xCorrelator, startTime, req.url, responseBody.took);
I raised a [query ](https://github.com/openBackhaul/ApplicationPattern/issues/663) regarding this. 
For now , I will mark this review comment as resolved. Further we shall proceed based on the decision in the issue. Thanks.

2023-04-25 10:24 UTC, PrathibaJee approved these changes
Thanks for fixing the review comments. 
Approving the changes.

2023-04-25 10:24 UTC, merged