issue-333 : ignore version conflicts
openBackhaul/ApplicationLayerTopology pull request #336
Opened 2023-06-05 13:48 UTC by DanaSunal

Fixes #333

2023-06-12 10:26 UTC, PrathibaJee requested changes
The issue is inconsistent.
Thank you @IswaryaaS for helping in reproducing the issue. Version conflit problem is resolved.


But ,  there is another problem which we noticed during testing.

/v1/update-fc is working fine individually.
But when /v1/update-fc is called along with /update-ltp as a callbacl from other applications , /update-fc is not working and throwing 500 internal error.

For example :
When we update an fc is directly to ALT , /v1/update-fc is working fine and response code is 204.
But when from EATL , if we regard a new application , a ltp and a fc will be created and forwarded to ALT. In this scenario , only /v1/update-ltp is working fine , where as /v1/update-fc is not working and throwing 500 internal server error.

Please reproduce this issue and resolve this in this same PR. Or create a separate issue and we shall close this PR as the original problem is resolved.

2023-06-19 11:27 UTC, DanaSunal commented
It is a different issue. Will open a new one, so please merge this one.

2023-06-22 08:26 UTC, PrathibaJee commented
Reviewer is @MartinSunal

2023-06-22 16:03 UTC, MartinSunal approved these changes

2023-06-22 16:03 UTC, merged