issue-319 : preparation
openBackhaul/ApplicationLayerTopology pull request #342
Opened 2023-06-09 15:03 UTC by DanaSunal

- some refactoring before the actual change, see commits

2023-06-12 07:53 UTC, DanaSunal commented
Please squash the commits when merging, no idea why there are duplicates.

2023-06-19 16:17 UTC, vanithavalluripalli9 requested changes
When we execute /v1/add-operation-client-to-link service at a time it is giving 500 Internal server error but the same if we are executing in debug environment means some delay will be added it is giving 200 response code . Could you please check if it is reproducible in your environment .

2023-06-20 06:46 UTC, DanaSunal commented
Found one issuei n LinkServices, fixed it.

2023-06-20 07:56 UTC, vanithavalluripalli9 approved these changes

2023-06-20 07:56 UTC, merged