resolve response-code is set as INTERNAL_SERVER_ERROR in catch block …
openBackhaul/ApplicationLayerTopology pull request #379
Opened 2023-06-26 10:00 UTC by ManasaBM1

…for all services

Fixes #346

2023-06-26 17:40 UTC, MartinSunal requested changes

2023-06-26 17:40 UTC, MartinSunal commented on server/service/individualServices/ForwardingService.js
> +const BadRequestHttpException = require('onf-core-model-ap/applicationPattern/rest/server/HttpException');
We will not use BadRequestHttpException anymore but http-errors library.
Please, wait until required changes are done in controllers and then you can change this service to use errors from http-errors.

2023-06-28 06:11 UTC, ManasaBM1 commented on server/service/individualServices/ForwardingService.js
> +const BadRequestHttpException = require('onf-core-model-ap/applicationPattern/rest/server/HttpException');
Ok Done

2023-06-28 07:22 UTC, MartinSunal requested changes

2023-06-28 07:22 UTC, MartinSunal commented on server/service/individualServices/ForwardingService.js
> +               throw new createHttpError.BadRequest("requested uuid does not exit")
pls, use uuid value as part of message and be more verbose e.g. (CC with uuid ${controlConstructUuid} does not exist.). Also, make sure you format code you changed properly (missing spaces....)
Obviously, this comment applies to other place too.

2023-06-28 07:24 UTC, MartinSunal commented
@ManasaBM1 Are there any other places in this app where we need to return http error? I am asking because this PR contains `Fixes #346` in description which will cause closing of the issue when this PR is merged.

2023-06-28 07:36 UTC, ManasaBM1 commented
> @ManasaBM1 Are there any other places in this app where we need to return http error? I am asking because this PR contains `Fixes #346` in description which will cause closing of the issue when this PR is merged.

 @MartinSunal Nope I think These are plcaes we need  include http error related basic and individual Services

2023-06-28 07:36 UTC, ManasaBM1 commented on server/service/individualServices/ForwardingService.js
> +               throw new createHttpError.BadRequest("requested uuid does not exit")
done

2023-06-28 07:51 UTC, MartinSunal approved these changes

2023-06-28 07:51 UTC, merged