issue-436 : send forwardings for link change in regard-application
openBackhaul/ApplicationLayerTopology pull request #453
Opened 2023-07-26 08:21 UTC by DanaSunal

Fixes #436

2023-08-05 14:39 UTC, PrathibaJee requested changes

2023-08-05 14:39 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +    forwardingAutomationInput,
automateForwardingConstructAsync in applicationPattern/onfModel/services/ForwardingConstructAutomationServices.js expects a list. So, making the list to object will not let the forwarding happen. Please let me know your views.

2023-08-05 14:39 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
I dont see a way to take the operationName(/v1/add-operation-client-to-link) from a forwarding (as LinkChangeNotification contains 2 input and we shall not relay on the local-id). If you too dont see a possibility to avoid hardcoding the operationName here , the we shall keep it as it is.

2023-08-05 14:39 UTC, PrathibaJee commented on server/service/individualServices/LinkServices.js
> +async function getLinkOfTheOperationAsync(operationUuid, portDirection) {
export is removed from this service getLinkOfTheOperationAsync definition. So , in the line.no 46,79 also the export keyword shall be removed , 
 let linkResponse =  await exports.getLinkOfTheOperationAsync(servingOperationUuid, LinkPort.portDirectionEnum.OUTPUT);

2023-08-06 08:50 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
What we can do, is call exports.addOperationClientToLink directly, without a forwarding. Since we are calling ALT to ALT, it makes more sense to call it directly, than to route the request through REST. Let me know your thoughts and I'll adjust the code.

```
  for (let operationServerName of operationServerNames) {
    let endPointDetails = {
      'serving-application-name': applicationName,
      'serving-application-release-number': releaseNumber,
      'operation-name': operationServerName
    }
    exports.addOperationClientToLink(endPointDetails, headers.user,
      headers.xCorrelator,
      headers.traceIndicator,
      headers.customerJourney);
}
```

2023-08-06 18:30 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
Yes this looks fine. Also , if this makes a record in the EATL application , that would help us to see the flow.

2023-08-07 07:44 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
I am afraid it doesn't. Record to EATL is being done in controller part and we are calling here the service.

2023-08-07 20:14 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
No problem. 
For now we shall then use the harcoded value as recording this flow in the EATL will make the process more transparent and we shall request for a forwarding for this scenario.
If you are fine with this , please raise a separate issue to include a new forwarding(/v1/regard-application --> /v1/add-operation-client-to-link) in the configuration file.

2023-08-08 08:05 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
I took a look at how add-operation-to-client is used right now. It's not used at all from any applications. The only usage is from update-ltp and that's again ALT->ALT. So my proposal would be that this operation should not be exposed at all and should be only internally part of update-ltp and regard-application. 
I really do not see any added value in recording internal application calls and we will still have the record from OKM.

2023-08-08 13:52 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +    "/v1/add-operation-client-to-link",
This two services add-operation-to-client, remove-operation-client-from-link will be used by an operator to provide access between applications.
Also , we have a plan to include a GUI for this ApplicationLayerTopology. This service add-operation-to-client, remove-operation-client-from-link will be used to adding/removing links by an operator.
So , we shall keep this services as it is.

2023-08-22 16:47 UTC, PrathibaJee approved these changes

2023-08-22 16:47 UTC, merged