Updated response-body of /v1/regard-application
openBackhaul/ApplicationLayerTopology pull request #574
Opened 2024-09-09 07:32 UTC by sunil-kumar-meena

Fixes
https://github.com/openBackhaul/ApplicationLayerTopology/issues/570

reviewer @PrathibaJee

2024-09-09 14:27 UTC, PrathibaJee requested changes
Please fix the review comments. Also after fixing the review comments, perform unit testing for the integer profile.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +  const value = await fileOperation.readFromDatabaseAsync(url);
fileOperation is not defined. please import it from the JSONDriver.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +  const value = await fileOperation.readFromDatabaseAsync(url);
fileOperation is not defined. please import it from the JSONDriver.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +      var value = await fileOperation.readFromDatabaseAsync(url);
fileOperation is not defined. please import it from the JSONDriver.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +    throw new createHttpError.BadRequest(`integer-profile-1-0:integer-value must be in range between ${minimumIntegerValue} and ${maximumIntegerValue}`)
'createHttpError' is not defined

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +  let profile = await IntegerProfile.getIntegerProfile(uuid);
'IntegerProfile' is not defined. Import Integer profile from the application pattern package.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +  const value = await fileOperation.readFromDatabaseAsync(url);
fileOperation is not defined. please import it from the JSONDriver.

2024-09-09 14:27 UTC, PrathibaJee commented on server/service/IntegerProfileService.js
> +  await fileOperation.writeToDatabaseAsync(url, body, false);
fileOperation is not defined. please import it from the JSONDriver.

2024-09-10 07:04 UTC, sunil-kumar-meena commented on server/service/IntegerProfileService.js
> +  const value = await fileOperation.readFromDatabaseAsync(url);
this is fixed

2024-09-10 07:08 UTC, PrathibaJee approved these changes
Thanks for fixing the review comments.

2024-09-10 07:08 UTC, merged