Updated response-body of /v1/regard-application
openBackhaul/ApplicationLayerTopology pull request #577
Opened 2024-09-11 10:31 UTC by sunil-kumar-meena

Fixes: 
https://github.com/openBackhaul/ApplicationLayerTopology/issues/570

Note: Last PR https://github.com/openBackhaul/ApplicationLayerTopology/pull/574 got merged into develop branch, raising new PR again, also suggest do we have to revert the last changes from develop branch also?

reviewer @PrathibaJee

2024-09-11 11:48 UTC, PrathibaJee requested changes

2024-09-11 11:48 UTC, PrathibaJee commented on server/service/individualServices/regardApplicationAutomation.js
> +      result["reason-of-failure"] = `ALT_DID_NOT_REACH_NEW_APPLICATION`;
if (!responseCode.toString().startsWith("2")) , then you have to check whether the if responseCode.toString() == "408" to confirm that the application is actually not reachable. ( Note : Include the response code for which a not reachable scenario happen)

2024-09-11 11:48 UTC, PrathibaJee commented on server/service/individualServices/regardApplicationAutomation.js
>      if (!responseCode.toString().startsWith("2")) {
if (!responseCode.toString().startsWith("2")) , then you have to check whether the if responseCode.toString() == "408" to confirm that the application is actually not reachable. ( Note : Include the response code for which a not reachable scenario happen)

2024-09-12 11:45 UTC, sunil-kumar-meena commented on server/service/individualServices/regardApplicationAutomation.js
> +      result["reason-of-failure"] = `ALT_DID_NOT_REACH_NEW_APPLICATION`;
done

2024-09-12 11:45 UTC, sunil-kumar-meena commented on server/service/individualServices/regardApplicationAutomation.js
>      if (!responseCode.toString().startsWith("2")) {
done

2024-09-18 07:17 UTC, PrathibaJee approved these changes

2024-09-18 07:17 UTC, merged