Handled ALT's register-yourself forwarding PromptForEmbeddingInitiatesEmbeddingProcess.RequestForBequeathingData
openBackhaul/ApplicationLayerTopology pull request #582
Opened 2024-09-24 05:33 UTC by sunil-kumar-meena

Fixes
https://github.com/openBackhaul/ApplicationLayerTopology/issues/581

2024-09-25 06:34 UTC, PrathibaJee requested changes

2024-09-25 06:34 UTC, PrathibaJee commented on server/controllers/BasicServices.js
> +  let beaqueathYourDataAndDieForwardingName = "PromptForEmbeddingInitiatesEmbeddingProcess.RequestForBequeathingData";
The constant OLD_RELEASE_FORWARDING_NAME defined in the starting of this file also holds the same forwardingName. Could you please reuse the constant.

2024-09-26 06:33 UTC, sunil-kumar-meena commented on server/controllers/BasicServices.js
> +  let beaqueathYourDataAndDieForwardingName = "PromptForEmbeddingInitiatesEmbeddingProcess.RequestForBequeathingData";
done

2024-09-30 11:13 UTC, PrathibaJee approved these changes

2024-09-30 11:13 UTC, merged