Translate ServiceList to yaml
openBackhaul/ApplicationLayerTopology pull request #99
Opened 2022-11-08 15:41 UTC by openBackhaul

2022-11-09 14:27 UTC, IswaryaaS requested changes

2022-11-09 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology+services.yaml
>            uuid: alt-1-0-0-op-s-2001
the service /v1/list-operation-clients-activated-by-operation-server-at-application (line 66) is named "/v1/list-operation-clients-reacting-on-operation-server" in OAS([ApplicationLayerTopology.yaml](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/ApplicationLayerTopology.yaml) and [ApplicationLayerTopology+data.json](https://github.com/openBackhaul/ApplicationLayerTopology/blob/develop/ApplicationLayerTopology_0.0.2_tsi.220110.1955%2Bdata.2.json)). 
Please let me know if this service name is also need to be updated in OAS and data.json file or the service name should be updated as "/v1/list-operation-clients-reacting-on-operation-server" in services.yaml file

2022-11-09 14:27 UTC, IswaryaaS commented on ApplicationLayerTopology+forwardings.yaml
> +    uuid: alt-1-0-0-op-fc-im-114
the uuid for PromptForBequeathingDataCausesRObeingRequestedToStopNotificationsToOldRelease can be updated to alt-1-0-0-op-fc-im-115 since PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease is also assigned with same uuid as alt-1-0-0-op-fc-im-114

2022-11-11 16:01 UTC, openBackhaul commented on ApplicationLayerTopology+services.yaml
> +        - service-name: /v1/start-application-in-generic-representation
Changed as proposed.

2022-11-11 16:02 UTC, openBackhaul commented on ApplicationLayerTopology+services.yaml
> +          uuid: alt-1-0-0-op-s-2000
Changed as proposed.

2022-11-11 16:03 UTC, openBackhaul commented on ApplicationLayerTopology+services.yaml
>          - service-name: /v1/inform-about-application
Changed as proposed.

2022-11-11 16:05 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +forwardings:
Changed as proposed.

2022-11-11 16:08 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +      - client-name: RegistryOffice:://v1/end-subscription
Changed as proposed.

2022-11-11 16:11 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +          uuid: alt-1-0-0-op-s-is-004
Changed as proposed.

2022-11-11 16:12 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +          uuid: alt-1-0-0-op-s-is-004
Changed as proposed.

2022-11-11 16:17 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +      - client-name: RegistryOffice:://v1/list-ltps-and-fcs
All occurences of //v1/list-ltps-and-fcs haven been changed to "individual service (is)"

2022-11-11 16:21 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +      - service-name: /v1/list-operation-clients-activated-by-operation-server-at-application
Changed ServiceList and ForwardingList towards _/v1/list-operation-clients-reacting-on-operation-server_.

2022-11-11 16:23 UTC, openBackhaul commented on ApplicationLayerTopology+services.yaml
>            uuid: alt-1-0-0-op-s-2001
Changed ServiceList and ForwardingList towards /v1/list-operation-clients-reacting-on-operation-server.

2022-11-11 16:24 UTC, openBackhaul commented on ApplicationLayerTopology+forwardings.yaml
> +    uuid: alt-1-0-0-op-fc-im-114
Changed as proposed.

2022-11-14 11:42 UTC, IswaryaaS approved these changes

2022-11-15 13:50 UTC, merged